#!/usr/bin/env bash
set -euo pipefail

DOTFILES="$(cd "$(dirname "$0")" && pwd)"

# Environment detection
detect_env() {
    if grep -qi microsoft /proc/version 2>/dev/null; then
        echo "wsl"
    elif [[ "$(uname)" == "Linux" ]]; then
        echo "linux"
    elif [[ "$(uname)" == "Darwin" ]]; then
        echo "mac"
    fi
}

ENV=$(detect_env)
echo "Detected environment: $ENV"

# Create symlinks recursively from src_dir to $HOME
link_files() {
    local src_dir="$1"

    find "$src_dir" -type f | while read -r src; do
        local rel="${src#$src_dir/}"
        local dest="$HOME/$rel"
        local dest_dir
        dest_dir="$(dirname "$dest")"

        mkdir -p "$dest_dir"

        if [[ -e "$dest" && ! -L "$dest" ]]; then
            echo "Backing up $dest -> $dest.bak"
            mv "$dest" "$dest.bak"
        elif [[ -L "$dest" ]]; then
            rm "$dest"
        fi

        ln -s "$src" "$dest"
        echo "Linked $rel"
    done
}

# Link common files
link_files "$DOTFILES/common"

# Link environment-specific files
if [[ -n "$ENV" && -d "$DOTFILES/$ENV" ]]; then
    link_files "$DOTFILES/$ENV"
fi

# Generate .bashrc
cat > "$HOME/.bashrc" <<EOF
# Auto-generated by dotfiles/install.sh
source "$DOTFILES/common/.bashrc_common"
[[ -f "$DOTFILES/$ENV/.bashrc_$ENV" ]] && source "$DOTFILES/$ENV/.bashrc_$ENV"
EOF

echo ""
echo "Done! Restart your shell or run: source ~/.bashrc"
