set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

set -g escape-time 0
set -g history-limit 100000
set -g mouse on
set -g focus-events on
set -g set-clipboard on

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

setw -g mode-keys vi
set -g status-keys vi

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel
